# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'urun_takip.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1230, 820)
        MainWindow.setMinimumSize(QtCore.QSize(1230, 820))
        MainWindow.setMaximumSize(QtCore.QSize(1230, 820))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("hcsYazilim.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color:#f0f0f0;\n"
"}\n"
"QCheckBox {\n"
"    padding:2px;\n"
"}\n"
"QCheckBox:hover {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    border-width:1px;\n"
"    padding-left: 1px;\n"
"    padding-right: 1px;\n"
"    padding-bottom: 1px;\n"
"    padding-top: 1px;\n"
"    border-color: rgb(255,150,60);\n"
"    background-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(190, 90, 50, 50), stop:1 rgba(250, 130, 40, 50));\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    border-width:1px;\n"
"    border-color: rgb(246, 134, 86);\n"
"      background-color:rgb(246, 134, 86)\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    border-width:1px;\n"
"    border-color:rgb(246, 134, 86);\n"
"      background-color:rgb(255,255,255);\n"
"}\n"
"QColorDialog {\n"
"    background-color:#f0f0f0;\n"
"}\n"
"QComboBox {\n"
"    color:rgb(81,72,65);\n"
"    background: #ffffff;\n"
"}\n"
"QComboBox:editable {\n"
"    background: #ffffff;\n"
"    color: rgb(81,72,65);\n"
"    selection-color:rgb(81,72,65);\n"
"    selection-background-color: #ffffff;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color:rgb(81,72,65);    \n"
"    background: #ffffff;\n"
"    selection-color: #ffffff;\n"
"    selection-background-color: rgb(246, 134, 86);\n"
"}\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    color:  #1e1d23;    \n"
"    background: #ffffff;\n"
"}\n"
"QDateTimeEdit {\n"
"    color:rgb(81,72,65);\n"
"    background-color: #ffffff;\n"
"}\n"
"QDateEdit {\n"
"    color:rgb(81,72,65);\n"
"    background-color: #ffffff;\n"
"}\n"
"QDialog {\n"
"    background-color:#f0f0f0;\n"
"}\n"
"QDoubleSpinBox {\n"
"    color:rgb(81,72,65);\n"
"    background-color: #ffffff;\n"
"}\n"
"QFontComboBox {\n"
"    color:rgb(81,72,65);\n"
"    background-color: #ffffff;\n"
"}\n"
"QLabel {\n"
"    color:rgb(17,17,17);\n"
"}\n"
"QLineEdit {\n"
"    background-color:rgb(255,255,255);\n"
"    selection-background-color:rgb(236,116,64);\n"
"    color:rgb(17,17,17);\n"
"}\n"
"QMenuBar {\n"
"    color:rgb(223,219,210);\n"
"    background-color:rgb(65,64,59);\n"
"}\n"
"QMenuBar::item {\n"
"    padding-top:4px;\n"
"    padding-left:4px;\n"
"    padding-right:4px;\n"
"    color:rgb(223,219,210);\n"
"    background-color:rgb(65,64,59);\n"
"}\n"
"QMenuBar::item:selected {\n"
"    color:rgb(255,255,255);\n"
"    padding-top:2px;\n"
"    padding-left:2px;\n"
"    padding-right:2px;\n"
"    border-top-width:2px;\n"
"    border-left-width:2px;\n"
"    border-right-width:2px;\n"
"    border-top-right-radius:4px;\n"
"    border-top-left-radius:4px;\n"
"    border-style:solid;\n"
"    background-color:rgb(65,64,59);\n"
"    border-top-color: rgb(47,47,44);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(90, 87, 78, 255), stop:1 rgba(47,47,44, 255));\n"
"    border-left-color:  qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(90, 87, 78, 255), stop:1 rgba(47,47,44, 255));\n"
"}\n"
"QMenu {\n"
"    color:rgb(223,219,210);\n"
"    background-color:rgb(65,64,59);\n"
"}\n"
"QMenu::item {\n"
"    color:rgb(223,219,210);\n"
"    padding-left:20px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    padding-right:10px;\n"
"}\n"
"QMenu::item:selected {\n"
"    color:rgb(255,255,255);\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(225, 108, 54, 255), stop:1 rgba(246, 134, 86, 255));\n"
"    border-style:solid;\n"
"    border-width:3px;\n"
"    padding-left:17px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    padding-right:7px;\n"
"    border-bottom-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(175,85,48,255), stop:1 rgba(236,114,67, 255));\n"
"    border-top-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"    border-right-color:qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"    border-left-color:qlineargradient(spread:pad, x1:1, y1:0.5, x2:0, y2:0.5, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"}\n"
"QPlainTextEdit {\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color:transparent;\n"
"    color:rgb(17,17,17);\n"
"    selection-background-color:rgb(236,116,64);\n"
"}\n"
"QProgressBar {\n"
"    text-align: center;\n"
"    color: rgb(0, 0, 0);\n"
"    border-width: 1px; \n"
"    border-radius: 10px;\n"
"    border-style: inset;\n"
"    border-color: rgb(150,150,150);\n"
"    background-color:rgb(221,221,219);\n"
"}\n"
"QProgressBar::chunk:horizontal {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(225, 108, 54, 255), stop:1 rgba(246, 134, 86, 255));\n"
"    border-style: solid;\n"
"    border-radius:8px;\n"
"    border-width:1px;\n"
"    border-bottom-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(175,85,48,255), stop:1 rgba(236,114,67, 255));\n"
"    border-top-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"    border-right-color:qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"    border-left-color:qlineargradient(spread:pad, x1:1, y1:0.5, x2:0, y2:0.5, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"}\n"
"QPushButton{\n"
"    color:rgb(17,17,17);\n"
"    border-width: 1px;\n"
"    border-radius: 6px;\n"
"    border-bottom-color: rgb(150,150,150);\n"
"    border-right-color: rgb(165,165,165);\n"
"    border-left-color: rgb(165,165,165);\n"
"    border-top-color: rgb(180,180,180);\n"
"    border-style: solid;\n"
"    padding: 4px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(220, 220, 220, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton:hover{\n"
"    color:rgb(17,17,17);\n"
"    border-width: 1px;\n"
"    border-radius:6px;\n"
"    border-top-color: rgb(255,150,60);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 255));\n"
"    border-left-color:  qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 255));\n"
"    border-bottom-color: rgb(200,70,20);\n"
"    border-style: solid;\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(220, 220, 220, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton:default{\n"
"    color:rgb(17,17,17);\n"
"    border-width: 1px;\n"
"    border-radius:6px;\n"
"    border-top-color: rgb(255,150,60);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 255));\n"
"    border-left-color:  qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 255));\n"
"    border-bottom-color: rgb(200,70,20);\n"
"    border-style: solid;\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(220, 220, 220, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton:pressed{\n"
"    color:rgb(17,17,17);\n"
"    border-width: 1px;\n"
"    border-radius: 6px;\n"
"    border-width: 1px;\n"
"    border-top-color: rgba(255,150,60,200);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 200));\n"
"    border-left-color:  qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 200));\n"
"    border-bottom-color: rgba(200,70,20,200);\n"
"    border-style: solid;\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(220, 220, 220, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton:disabled{\n"
"    color:rgb(174,167,159);\n"
"    border-width: 1px;\n"
"    border-radius: 6px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(200, 200, 200, 255), stop:1 rgba(230, 230, 230, 255));\n"
"}\n"
"QRadioButton {\n"
"    padding: 1px;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: rgba(246, 134, 86, 255);\n"
"    color: #a9b7c6;\n"
"    background-color:rgba(246, 134, 86, 255);\n"
"}\n"
"QRadioButton::indicator:!checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: rgb(246, 134, 86);\n"
"    color: #a9b7c6;\n"
"    background-color: transparent;\n"
"}\n"
"QScrollArea {\n"
"    color: #FFFFFF;\n"
"    background-color:#f0f0f0;\n"
"}\n"
"QSlider::groove {\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    height: 5px;\n"
"    background: rgb(246, 134, 86);\n"
"}\n"
"QSlider::groove:vertical {\n"
"    width: 5px;\n"
"    background: rgb(246, 134, 86);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    width: 12px;\n"
"    margin: -5px 0;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    height: 12px;\n"
"    margin: 0 -5px;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::add-page:horizontal {\n"
"     background: white;\n"
"}\n"
"QSlider::add-page:vertical {\n"
"    background: white;\n"
"}\n"
"QSlider::sub-page:horizontal {\n"
"    background: rgb(246, 134, 86);\n"
"}\n"
"QSlider::sub-page:vertical {\n"
"      background: rgb(246, 134, 86);\n"
"}\n"
"QStatusBar {\n"
"    color:rgb(81,72,65);\n"
"}\n"
"QSpinBox {\n"
"    color:rgb(81,72,65);\n"
"    background-color: #ffffff;\n"
"}\n"
"QScrollBar:horizontal {\n"
"    max-height: 20px;\n"
"    border: 1px transparent grey;\n"
"    margin: 0px 20px 0px 20px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    border-radius: 7px;\n"
"    min-width: 25px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(255,150,60);\n"
"    border-radius: 7px;\n"
"    min-width: 25px;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"      border: 1px solid;\n"
"      border-color: rgb(207,207,207);\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-right-radius: 7px;\n"
"      background: rgb(255, 255, 255);\n"
"      width: 20px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:hover {\n"
"      border: 1px solid;\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-right-radius: 7px;\n"
"      border-color: rgb(255,150,60);\n"
"      background: rgb(255, 255, 255);\n"
"      width: 20px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {\n"
"      border: 1px solid grey;\n"
"      border-top-left-radius: 7px;\n"
"      border-top-right-radius: 7px;\n"
"      border-bottom-right-radius: 7px;\n"
"      background: rgb(231,231,231);\n"
"      width: 20px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"      border: 1px solid;\n"
"      border-color: rgb(207,207,207);\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"      background: rgb(255, 255, 255);\n"
"      width: 20px;\n"
"      subcontrol-position: left;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {\n"
"      border: 1px solid;\n"
"      border-color: rgb(255,150,60);\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"      background: rgb(255, 255, 255);\n"
"      width: 20px;\n"
"      subcontrol-position: left;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {\n"
"      border: 1px solid grey;\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"      background: rgb(231,231,231);\n"
"      width: 20px;\n"
"      subcontrol-position: left;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::left-arrow:horizontal {\n"
"      border: 1px transparent grey;\n"
"      border-top-left-radius: 3px;\n"
"      border-bottom-left-radius: 3px;\n"
"      width: 6px;\n"
"      height: 6px;\n"
"      background: rgb(230,230,230);\n"
"}\n"
"QScrollBar::right-arrow:horizontal {\n"
"    border: 1px transparent grey;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"      width: 6px;\n"
"      height: 6px;\n"
"     background: rgb(230,230,230);\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"     background: none;\n"
"} \n"
"QScrollBar:vertical {\n"
"    max-width: 20px;\n"
"    border: 1px transparent grey;\n"
"    margin: 20px 0px 20px 0px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    border: 1px solid;\n"
"    border-color: rgb(207,207,207);\n"
"    border-bottom-right-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-top-left-radius: 7px;\n"
"    background: rgb(255, 255, 255);\n"
"      height: 20px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {\n"
"      border: 1px solid;\n"
"      border-color: rgb(255,150,60);\n"
"      border-bottom-right-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      background: rgb(255, 255, 255);\n"
"      height: 20px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {\n"
"      border: 1px solid grey;\n"
"      border-bottom-left-radius: 7px;\n"
"      border-bottom-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      background: rgb(231,231,231);\n"
"      height: 20px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"      border: 1px solid;\n"
"      border-color: rgb(207,207,207);\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"      background: rgb(255, 255, 255);\n"
"      height: 20px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {\n"
"      border: 1px solid;\n"
"      border-color: rgb(255,150,60);\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"    background: rgb(255, 255, 255);\n"
"      height: 20px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {\n"
"      border: 1px solid grey;\n"
"      border-top-left-radius: 7px;\n"
"      border-top-right-radius: 7px;\n"
"      background: rgb(231,231,231);\n"
"     height: 20px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    border-radius: 7px;\n"
"    min-height: 25px;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(255,150,60);\n"
"    border-radius: 7px;\n"
"    min-height: 25px;\n"
"}\n"
"QScrollBar::up-arrow:vertical {\n"
"    border: 1px transparent grey;\n"
"      border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"      width: 6px;\n"
"      height: 6px;\n"
"      background: rgb(230,230,230);\n"
"}\n"
"QScrollBar::down-arrow:vertical {\n"
"      border: 1px transparent grey;\n"
"      border-bottom-left-radius: 3px;\n"
"      border-bottom-right-radius: 3px;\n"
"      width: 6px;\n"
"      height: 6px;\n"
"      background: rgb(230,230,230);\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"      background: none;\n"
"}\n"
"QTabWidget {\n"
"    color:rgb(0,0,0);\n"
"    background-color:rgb(247,246,246);\n"
"}\n"
"QTabWidget::pane {\n"
"    border-color: rgb(180,180,180);\n"
"    background-color:rgb(247,246,246);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"      border-radius: 6px;\n"
"}\n"
"QTabBar::tab {\n"
"    padding-left:4px;\n"
"    padding-right:4px;\n"
"    padding-bottom:2px;\n"
"    padding-top:2px;\n"
"    color:rgb(81,72,65);\n"
"      background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(221,218,217,255), stop:1 rgba(240,239,238,255));\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"      border-top-right-radius:4px;\n"
"    border-top-left-radius:4px;\n"
"    border-top-color: rgb(180,180,180);\n"
"    border-left-color: rgb(180,180,180);\n"
"    border-right-color: rgb(180,180,180);\n"
"    border-bottom-color: transparent;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:last:selected, QTabBar::tab:hover {\n"
"      background-color:rgb(247,246,246);\n"
"      margin-left: 0px;\n"
"      margin-right: 1px;\n"
"}\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 1px;\n"
"    margin-right: 1px;\n"
"}\n"
"QTextEdit {\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color:transparent;\n"
"    color:rgb(17,17,17);\n"
"    selection-background-color:rgb(236,116,64);\n"
"}\n"
"QTimeEdit {\n"
"    color:rgb(81,72,65);\n"
"    background-color: #ffffff;\n"
"}\n"
"QToolBox {\n"
"    color:rgb(81,72,65);\n"
"    background-color: #ffffff;\n"
"}\n"
"QToolBox::tab {\n"
"    color:rgb(81,72,65);\n"
"    background-color: #ffffff;\n"
"}\n"
"QToolBox::tab:selected {\n"
"    color:rgb(81,72,65);\n"
"    background-color: #ffffff;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.grpUrunBilgileri = QtWidgets.QGroupBox(self.centralwidget)
        self.grpUrunBilgileri.setGeometry(QtCore.QRect(40, 40, 451, 381))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.grpUrunBilgileri.setFont(font)
        self.grpUrunBilgileri.setObjectName("grpUrunBilgileri")
        self.layoutWidget = QtWidgets.QWidget(self.grpUrunBilgileri)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 30, 391, 321))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblUrunTuru = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lblUrunTuru.setFont(font)
        self.lblUrunTuru.setObjectName("lblUrunTuru")
        self.horizontalLayout.addWidget(self.lblUrunTuru)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cmbUrunTuru = QtWidgets.QComboBox(self.layoutWidget)
        self.cmbUrunTuru.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.cmbUrunTuru.setFont(font)
        self.cmbUrunTuru.setEditable(False)
        self.cmbUrunTuru.setPlaceholderText("")
        self.cmbUrunTuru.setDuplicatesEnabled(False)
        self.cmbUrunTuru.setObjectName("cmbUrunTuru")
        self.cmbUrunTuru.addItem("")
        self.cmbUrunTuru.addItem("")
        self.horizontalLayout.addWidget(self.cmbUrunTuru)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblUrunModeli = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lblUrunModeli.setFont(font)
        self.lblUrunModeli.setObjectName("lblUrunModeli")
        self.horizontalLayout_2.addWidget(self.lblUrunModeli)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.cmbUrunModeli = QtWidgets.QComboBox(self.layoutWidget)
        self.cmbUrunModeli.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.cmbUrunModeli.setFont(font)
        self.cmbUrunModeli.setObjectName("cmbUrunModeli")
        self.cmbUrunModeli.addItem("")
        self.cmbUrunModeli.addItem("")
        self.cmbUrunModeli.addItem("")
        self.cmbUrunModeli.addItem("")
        self.cmbUrunModeli.addItem("")
        self.cmbUrunModeli.addItem("")
        self.cmbUrunModeli.addItem("")
        self.cmbUrunModeli.addItem("")
        self.cmbUrunModeli.addItem("")
        self.cmbUrunModeli.addItem("")
        self.cmbUrunModeli.addItem("")
        self.cmbUrunModeli.addItem("")
        self.cmbUrunModeli.addItem("")
        self.horizontalLayout_2.addWidget(self.cmbUrunModeli)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblUrunAdi = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lblUrunAdi.setFont(font)
        self.lblUrunAdi.setObjectName("lblUrunAdi")
        self.horizontalLayout_3.addWidget(self.lblUrunAdi)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.lneUrunAdi = QtWidgets.QLineEdit(self.layoutWidget)
        self.lneUrunAdi.setMinimumSize(QtCore.QSize(170, 0))
        self.lneUrunAdi.setObjectName("lneUrunAdi")
        self.horizontalLayout_3.addWidget(self.lneUrunAdi)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lblUrunNu = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lblUrunNu.setFont(font)
        self.lblUrunNu.setObjectName("lblUrunNu")
        self.horizontalLayout_4.addWidget(self.lblUrunNu)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.cmbUrunNu = QtWidgets.QComboBox(self.layoutWidget)
        self.cmbUrunNu.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.cmbUrunNu.setFont(font)
        self.cmbUrunNu.setObjectName("cmbUrunNu")
        self.cmbUrunNu.addItem("")
        self.cmbUrunNu.addItem("")
        self.cmbUrunNu.addItem("")
        self.cmbUrunNu.addItem("")
        self.cmbUrunNu.addItem("")
        self.cmbUrunNu.addItem("")
        self.cmbUrunNu.addItem("")
        self.cmbUrunNu.addItem("")
        self.cmbUrunNu.addItem("")
        self.horizontalLayout_4.addWidget(self.cmbUrunNu)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lblUrunRengi = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lblUrunRengi.setFont(font)
        self.lblUrunRengi.setObjectName("lblUrunRengi")
        self.horizontalLayout_5.addWidget(self.lblUrunRengi)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.cmbUrunRengi = QtWidgets.QComboBox(self.layoutWidget)
        self.cmbUrunRengi.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.cmbUrunRengi.setFont(font)
        self.cmbUrunRengi.setObjectName("cmbUrunRengi")
        self.cmbUrunRengi.addItem("")
        self.cmbUrunRengi.addItem("")
        self.cmbUrunRengi.addItem("")
        self.cmbUrunRengi.addItem("")
        self.cmbUrunRengi.addItem("")
        self.cmbUrunRengi.addItem("")
        self.cmbUrunRengi.addItem("")
        self.cmbUrunRengi.addItem("")
        self.cmbUrunRengi.addItem("")
        self.cmbUrunRengi.addItem("")
        self.cmbUrunRengi.addItem("")
        self.horizontalLayout_5.addWidget(self.cmbUrunRengi)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lblUrunAdedi = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lblUrunAdedi.setFont(font)
        self.lblUrunAdedi.setObjectName("lblUrunAdedi")
        self.horizontalLayout_6.addWidget(self.lblUrunAdedi)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.spnUrunAdedi = QtWidgets.QSpinBox(self.layoutWidget)
        self.spnUrunAdedi.setMinimumSize(QtCore.QSize(70, 0))
        self.spnUrunAdedi.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.spnUrunAdedi.setFont(font)
        self.spnUrunAdedi.setObjectName("spnUrunAdedi")
        self.horizontalLayout_6.addWidget(self.spnUrunAdedi)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.grpUrunTablosu = QtWidgets.QGroupBox(self.centralwidget)
        self.grpUrunTablosu.setGeometry(QtCore.QRect(520, 40, 671, 691))
        self.grpUrunTablosu.setMinimumSize(QtCore.QSize(0, 0))
        self.grpUrunTablosu.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.grpUrunTablosu.setFont(font)
        self.grpUrunTablosu.setObjectName("grpUrunTablosu")
        self.tblUrunTablosu = QtWidgets.QTableWidget(self.grpUrunTablosu)
        self.tblUrunTablosu.setGeometry(QtCore.QRect(30, 30, 611, 631))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.tblUrunTablosu.setFont(font)
        self.tblUrunTablosu.setRowCount(40)
        self.tblUrunTablosu.setColumnCount(7)
        self.tblUrunTablosu.setObjectName("tblUrunTablosu")
        self.grpAraclar = QtWidgets.QGroupBox(self.centralwidget)
        self.grpAraclar.setGeometry(QtCore.QRect(40, 440, 451, 291))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.grpAraclar.setFont(font)
        self.grpAraclar.setObjectName("grpAraclar")
        self.dgmSil = QtWidgets.QPushButton(self.grpAraclar)
        self.dgmSil.setGeometry(QtCore.QRect(170, 40, 120, 50))
        self.dgmSil.setMinimumSize(QtCore.QSize(120, 50))
        self.dgmSil.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.dgmSil.setFont(font)
        self.dgmSil.setObjectName("dgmSil")
        self.dgmAra = QtWidgets.QPushButton(self.grpAraclar)
        self.dgmAra.setGeometry(QtCore.QRect(302, 110, 121, 30))
        self.dgmAra.setMinimumSize(QtCore.QSize(0, 30))
        self.dgmAra.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.dgmAra.setFont(font)
        self.dgmAra.setObjectName("dgmAra")
        self.dgmCik = QtWidgets.QPushButton(self.grpAraclar)
        self.dgmCik.setGeometry(QtCore.QRect(302, 200, 121, 70))
        self.dgmCik.setMinimumSize(QtCore.QSize(70, 70))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.dgmCik.setFont(font)
        self.dgmCik.setObjectName("dgmCik")
        self.dgmEkle = QtWidgets.QPushButton(self.grpAraclar)
        self.dgmEkle.setGeometry(QtCore.QRect(40, 40, 120, 50))
        self.dgmEkle.setMinimumSize(QtCore.QSize(120, 50))
        self.dgmEkle.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.dgmEkle.setFont(font)
        self.dgmEkle.setObjectName("dgmEkle")
        self.lneAra = QtWidgets.QLineEdit(self.grpAraclar)
        self.lneAra.setGeometry(QtCore.QRect(40, 110, 251, 30))
        self.lneAra.setMinimumSize(QtCore.QSize(0, 30))
        self.lneAra.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lneAra.setFont(font)
        self.lneAra.setObjectName("lneAra")
        self.dgmGuncelle = QtWidgets.QPushButton(self.grpAraclar)
        self.dgmGuncelle.setGeometry(QtCore.QRect(300, 40, 120, 50))
        self.dgmGuncelle.setMinimumSize(QtCore.QSize(120, 50))
        self.dgmGuncelle.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.dgmGuncelle.setFont(font)
        self.dgmGuncelle.setObjectName("dgmGuncelle")
        self.dgmTemizle = QtWidgets.QPushButton(self.grpAraclar)
        self.dgmTemizle.setGeometry(QtCore.QRect(300, 150, 121, 30))
        self.dgmTemizle.setMinimumSize(QtCore.QSize(0, 30))
        self.dgmTemizle.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.dgmTemizle.setFont(font)
        self.dgmTemizle.setObjectName("dgmTemizle")
        self.layoutWidget1 = QtWidgets.QWidget(self.grpAraclar)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 210, 221, 24))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lblToplaUrunBildirgec = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lblToplaUrunBildirgec.setFont(font)
        self.lblToplaUrunBildirgec.setObjectName("lblToplaUrunBildirgec")
        self.horizontalLayout_8.addWidget(self.lblToplaUrunBildirgec)
        self.lblToplamUrunSayisi = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lblToplamUrunSayisi.setFont(font)
        self.lblToplamUrunSayisi.setText("")
        self.lblToplamUrunSayisi.setObjectName("lblToplamUrunSayisi")
        self.horizontalLayout_8.addWidget(self.lblToplamUrunSayisi)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(80, 680, 181, 24))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lblKayitBildirgec = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lblKayitBildirgec.setFont(font)
        self.lblKayitBildirgec.setObjectName("lblKayitBildirgec")
        self.horizontalLayout_7.addWidget(self.lblKayitBildirgec)
        self.lblKayitSayisi = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lblKayitSayisi.setFont(font)
        self.lblKayitSayisi.setText("")
        self.lblKayitSayisi.setObjectName("lblKayitSayisi")
        self.horizontalLayout_7.addWidget(self.lblKayitSayisi)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menucubugu = QtWidgets.QMenuBar(MainWindow)
        self.menucubugu.setGeometry(QtCore.QRect(0, 0, 1230, 25))
        self.menucubugu.setObjectName("menucubugu")
        self.menuYardim = QtWidgets.QMenu(self.menucubugu)
        self.menuYardim.setObjectName("menuYardim")
        self.menuHakkinda = QtWidgets.QMenu(self.menuYardim)
        self.menuHakkinda.setObjectName("menuHakkinda")
        MainWindow.setMenuBar(self.menucubugu)
        self.durumcubugu = QtWidgets.QStatusBar(MainWindow)
        self.durumcubugu.setObjectName("durumcubugu")
        MainWindow.setStatusBar(self.durumcubugu)
        self.actionHcs = QtWidgets.QAction(MainWindow)
        self.actionHcs.setObjectName("actionHcs")
        self.actHcsYazilim = QtWidgets.QAction(MainWindow)
        self.actHcsYazilim.setObjectName("actHcsYazilim")
        self.menuHakkinda.addAction(self.actHcsYazilim)
        self.menuYardim.addAction(self.menuHakkinda.menuAction())
        self.menucubugu.addAction(self.menuYardim.menuAction())

        self.retranslateUi(MainWindow)
        self.cmbUrunTuru.setCurrentIndex(-1)
        self.cmbUrunModeli.setCurrentIndex(-1)
        self.cmbUrunNu.setCurrentIndex(-1)
        self.cmbUrunRengi.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ürün Takip Uygulaması"))
        self.grpUrunBilgileri.setTitle(_translate("MainWindow", "Ürün Bilgileri"))
        self.lblUrunTuru.setText(_translate("MainWindow", "Ürün Türü:"))
        self.cmbUrunTuru.setItemText(0, _translate("MainWindow", "Kadın Ayakkabısı"))
        self.cmbUrunTuru.setItemText(1, _translate("MainWindow", "Erkek Ayakkabısı"))
        self.lblUrunModeli.setText(_translate("MainWindow", "Ürün Modeli:"))
        self.cmbUrunModeli.setItemText(0, _translate("MainWindow", "K-A550"))
        self.cmbUrunModeli.setItemText(1, _translate("MainWindow", "K-A570"))
        self.cmbUrunModeli.setItemText(2, _translate("MainWindow", "K-B300"))
        self.cmbUrunModeli.setItemText(3, _translate("MainWindow", "K-C340"))
        self.cmbUrunModeli.setItemText(4, _translate("MainWindow", "K-C450"))
        self.cmbUrunModeli.setItemText(5, _translate("MainWindow", "K-C700"))
        self.cmbUrunModeli.setItemText(6, _translate("MainWindow", "K-C800"))
        self.cmbUrunModeli.setItemText(7, _translate("MainWindow", "K-D270"))
        self.cmbUrunModeli.setItemText(8, _translate("MainWindow", "K-E350"))
        self.cmbUrunModeli.setItemText(9, _translate("MainWindow", "E-A600"))
        self.cmbUrunModeli.setItemText(10, _translate("MainWindow", "E-B350"))
        self.cmbUrunModeli.setItemText(11, _translate("MainWindow", "E-B570"))
        self.cmbUrunModeli.setItemText(12, _translate("MainWindow", "E-C630"))
        self.lblUrunAdi.setText(_translate("MainWindow", "Ürün Adı:"))
        self.lblUrunNu.setText(_translate("MainWindow", "Ürün Numarası:"))
        self.cmbUrunNu.setItemText(0, _translate("MainWindow", "35"))
        self.cmbUrunNu.setItemText(1, _translate("MainWindow", "36"))
        self.cmbUrunNu.setItemText(2, _translate("MainWindow", "37"))
        self.cmbUrunNu.setItemText(3, _translate("MainWindow", "38"))
        self.cmbUrunNu.setItemText(4, _translate("MainWindow", "39"))
        self.cmbUrunNu.setItemText(5, _translate("MainWindow", "40"))
        self.cmbUrunNu.setItemText(6, _translate("MainWindow", "41"))
        self.cmbUrunNu.setItemText(7, _translate("MainWindow", "42"))
        self.cmbUrunNu.setItemText(8, _translate("MainWindow", "43"))
        self.lblUrunRengi.setText(_translate("MainWindow", "Ürün Rengi:"))
        self.cmbUrunRengi.setItemText(0, _translate("MainWindow", "Siyah"))
        self.cmbUrunRengi.setItemText(1, _translate("MainWindow", "Mavi"))
        self.cmbUrunRengi.setItemText(2, _translate("MainWindow", "Lacivert"))
        self.cmbUrunRengi.setItemText(3, _translate("MainWindow", "Turkuvaz"))
        self.cmbUrunRengi.setItemText(4, _translate("MainWindow", "Sarı"))
        self.cmbUrunRengi.setItemText(5, _translate("MainWindow", "Beyaz"))
        self.cmbUrunRengi.setItemText(6, _translate("MainWindow", "Mor"))
        self.cmbUrunRengi.setItemText(7, _translate("MainWindow", "Pembe"))
        self.cmbUrunRengi.setItemText(8, _translate("MainWindow", "Kahve"))
        self.cmbUrunRengi.setItemText(9, _translate("MainWindow", "Yeşil"))
        self.cmbUrunRengi.setItemText(10, _translate("MainWindow", "Gri"))
        self.lblUrunAdedi.setText(_translate("MainWindow", "Ürün Adedi:"))
        self.grpUrunTablosu.setTitle(_translate("MainWindow", "Ürün Tablosu"))
        self.grpAraclar.setTitle(_translate("MainWindow", "Araçlar"))
        self.dgmSil.setText(_translate("MainWindow", "Sil"))
        self.dgmAra.setText(_translate("MainWindow", "Ara"))
        self.dgmCik.setText(_translate("MainWindow", "Çık"))
        self.dgmEkle.setText(_translate("MainWindow", "Ekle"))
        self.dgmGuncelle.setText(_translate("MainWindow", "Güncelle"))
        self.dgmTemizle.setText(_translate("MainWindow", "Temizle"))
        self.lblToplaUrunBildirgec.setText(_translate("MainWindow", "Toplam Ürün Sayısı:"))
        self.lblKayitBildirgec.setText(_translate("MainWindow", "Kayıt Sayısı:"))
        self.menuYardim.setTitle(_translate("MainWindow", "Yardım"))
        self.menuHakkinda.setTitle(_translate("MainWindow", "Hakkında"))
        self.actionHcs.setText(_translate("MainWindow", "Haluk Çağatay Sarıoğlu"))
        self.actHcsYazilim.setText(_translate("MainWindow", "hçsYazılım"))
